### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by Cellane**

### CODE REVIEW

**Comment by siemensikkema** [comment]
@Cellane thanks for the PR. The change is 👍 but Circle CI needs to be updated as well to make the checks pass. For reference, see: https://github.com/vapor/vapor/blob/beta/circle.yml.

**Comment by Cellane** [comment]
Aha, didn't know it's possible to run your own version of Swift on CircleCI, I'll adjust the configuration file accordingly! It seems I'll have to temporarily disable the macOS tests though (until the final version of Xcode 9.3 with final Swift 4.1 is released), I hope that's fine.

**Comment by siemensikkema** [comment]
I think it's safe to go with whatever is configured for the Vapor package but I have no inside knowledge on that.

**Comment by siemensikkema** [comment]
Thanks!

**Pull request merged**
